### ISSUE TITLE
Makefile incomplete

### ISSUE THREAD

**Issue by SeriousM** [bipio-server/bipio-docs#1]
Hi!

The Makefile states

>`include ../wot-make/npm.mk`

but I can't find it - neither in this repository nor somewhere on github.
Could we please get the file or at least the information if it's necessary at all?

Thank you!

**Comment by sburr** [comment]
The make system was just one of the areas that were a bit of a mess. Getting the stack up and running and cleaning it up is going to take a bit of elbow grease, I'm afraid.

**Comment by SeriousM** [comment]
No problem, I guess I will just change the layout to something simple then
